#!/bin/bash

set -ex

export CXXFLAGS="${CXXFLAGS} -std=c++11"
if [ "$(uname)" == "Linux" ]; then
    export LDFLAGS="${LDFLAGS} -Wl,-rpath-link,${PREFIX}/lib"
    export FFMPEG=ON
else
    export FFMPEG=OFF
fi

mkdir -p build

cmake $CMAKE_ARGS \
    -B "build" \
    -G "Ninja" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_LIBRARY_PATH=$PREFIX/lib \
    -DCMAKE_INCLUDE_PATH=$PREFIX/include \
    -DCCCORELIB_SCALAR_DOUBLE=ON \
    -DEIGEN_ROOT_DIR="$PREFIX/include/eigen3" \
    -DOPTION_SUPPORT_GAMEPADS=ON \
    -DOPTION_USE_SHAPE_LIB=ON \
    -DOPTION_USE_GDAL=ON \
    -DPLUGIN_EXAMPLE_GL=ON \
    -DPLUGIN_EXAMPLE_IO=ON \
    -DPLUGIN_EXAMPLE_STANDARD=ON \
    -DPLUGIN_GL_QEDL=ON \
    -DPLUGIN_GL_QSSAO=ON \
    -DPLUGIN_IO_QADDITIONAL=ON \
    -DPLUGIN_IO_QCORE=ON \
    -DPLUGIN_IO_QE57=OFF \
    -DPLUGIN_IO_QPHOTOSCAN=ON \
    -DPLUGIN_IO_QPDAL=ON \
    -DPLUGIN_IO_QRDB=OFF \
    -DPLUGIN_STANDARD_QANIMATION=ON \
    -DQANIMATION_WITH_FFMPEG_SUPPORT=$FFMPEG \
    -DPLUGIN_STANDARD_QBROOM=ON \
    -DPLUGIN_STANDARD_QCANUPO=OFF \
    -DPLUGIN_STANDARD_QCOMPASS=ON \
    -DPLUGIN_STANDARD_QCSF=ON \
    -DPLUGIN_STANDARD_QFACETS=ON \
    -DPLUGIN_STANDARD_QHOUGH_NORMALS=ON \
    -DPLUGIN_STANDARD_QHPR=ON \
    -DPLUGIN_STANDARD_QM3C2=ON \
    -DPLUGIN_STANDARD_QPCV=ON \
    -DPLUGIN_STANDARD_QPOISSON_RECON=OFF \
    -DPLUGIN_STANDARD_QSRA=OFF \
    -DPLUGIN_STANDARD_QRANSAC_SD=ON \
    -DPLUGIN_STANDARD_QPCL=OFF \
    .

cmake --build build
cd build && ninja

cmake -LA .
ninja install

